---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  namespace: nginx

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: nginx

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: nginx
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: nginx

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - args:
        - --source=service
        - --source=ingress
        - --domain-filter=1es.io
        - --provider=azure
        - --azure-resource-group=compes-bedrock-lab
        - --txt-owner-id=compes-bedrock-lab-westus2
        - --log-level=debug
        - --policy=sync
        image: oneesdevacr.azurecr.io/1es/external-dns:638873
        name: external-dns
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 25Mi
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: azure-config-file
          readOnly: true
      imagePullSecrets:
      - name: acr-auth
      serviceAccountName: external-dns
      volumes:
      - name: azure-config-file
        secret:
          secretName: external-dns-config-file

