---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-api
  labels:
    app: product-catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-api
  template:
    metadata:
      labels:
        app: product-catalog-api
    spec:
      containers:
        - name: product-catalog-api
          image: "oneesdevacr.azurecr.io/1es/product-catalog-api:{{ .Values.image.tag }}"
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "800Mi"
              cpu: "750m"
          securityContext:
            capabilities:
              drop:
              - all
          livenessProbe:
            httpGet:
              path: "/status"
              port: 6001
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: "/status"
              port: 6001
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "{{.Values.env.ASPNETCORE_ENVIRONMENT}}"
            - name: "tenant"
              value: "{{.Values.env.tenant}}"
            - name: "role"
              value: "{{.Values.env.role}}"
          ports:
          - containerPort: 6001
            protocol: TCP

      imagePullSecrets:
        - name: acr-auth
