---
# Source: chart/templates/azurekeyvaultsecret.yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: geneva-certificate
  namespace: geneva
spec:
  vault:
    name: compes-bedrock-kv
    object:
      name: Geneva-Certificate-Managed
      type: certificate
  output:
    secret:
      name: geneva-certificate
      type: kubernetes.io/tls
