config:
subcomponents:
  product-catalog-api:
    config:
      acr:
        name: xiaodolibedrockacr
      image:
        name: product-catalog-api
        tag: "370656"
      dns:
        domain: 1es.io
        sslCert: sslcert-1es-io
      env:
        ASPNETCORE_ENVIRONMENT: Integration
        ROLE: Development
  product-catalog-sync-job:
    config:
      acr:
        name: xiaodolibedrockacr
      image:
        name: product-catalog-sync-job
        tag: "585213"
      env:
        ASPNETCORE_ENVIRONMENT: Integration
        ROLE: Development
  product-catalog-web:
    config:
      acr:
        name: xiaodolibedrockacr
      image:
        name: product-catalog-web
        tag: "373647"
      dns:
        domain: 1es.io
        sslCert: sslcert-1es-io
      env:
        ASPNETCORE_ENVIRONMENT: Integration
        ROLE: Development
  secret-broker:
    config:
      acr:
        name: xiaodolibedrockacr
      image:
        name: secret-broker
        tag: "720313"
      env:
        ASPNETCORE_ENVIRONMENT: Integration
        ROLE: Development