---
# Source: chart/templates/azurekeyvaultsecret.yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: tls-cert
  namespace: default
spec:
  vault:
    name: compes-bedrock-kv
    object:
      name: 1es-io-tls-cert
      type: certificate
  output:
    secret:
      name: tls-cert
