---
# Source: chart/templates/servicemonitors.yaml

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-metrics-servicemonitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ingress-nginx
    team: infra
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      release: prometheus-operator
  namespaceSelector:
    matchNames:
      - ingress-nginx
    any: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-metrics-servicemonitor
  namespace: monitoring
  labels:
    app: flux
    team: infra
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: flux
      release: prometheus-operator
  namespaceSelector:
    matchNames:
      - flux
    any: true
  endpoints:
  - port: http
    interval: 15s
