---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-web
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 6002
    name: "product-catalog-web-https"
  selector:
    app: product-catalog-web