---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-broker
  labels:
    app: secret-broker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secret-broker
  template:
    metadata:
      labels:
        app: secret-broker
    spec:
      # Needs to run in production as root, because azure.json is root-only
      securityContext:
        runAsUser: 0
      containers:
        - name: secret-broker
          image: {{.Values.acr.name}}.azurecr.io/{{.Values.image.name}}:{{ .Values.image.tag }}
          resources:
            requests:
              cpu: "50m"
              memory: "75Mi"
            limits:
              cpu: "100m"
              memory: "250Mi"
          env:
            - name: TENANT
              value: "{{.Values.env.tenant}}"
            - name: ROLE
              value: "{{.Values.env.role}}"
          livenessProbe:
            httpGet:
              port: 20000
              path: /status
              scheme: HTTPS
            initialDelaySeconds: 5
          volumeMounts:
            - name: ad-creds
              mountPath: /secrets/ad-creds
              readOnly: true
            - name: cert
              mountPath: /secrets/cert
              readOnly: true
      volumes:
        - name: ad-creds
          hostPath:
            path: /etc/kubernetes
        - name: cert
          secret:
            secretName: ssl-aks-default-certificate