---
apiVersion: v1
kind: Service
metadata:
  name: secret-broker
spec:
  type: ClusterIP
  ports:
    - name: service-broker-https
      protocol: TCP
      port: 443
      targetPort: 20000
  selector:
    app: secret-broker